### ISSUE TITLE
UCI_Elo and UCI_Limit meaning

### ISSUE THREAD

**Issue by tissatussa** [Adam-Kulju/Patricia#24]
i'm enthousiastic about the new version v3.0 ! Your README gives remarkable details.

there's a small bug in your settings : the `UCI_Elo` and `UCI_Limit` options are not shown in the CuteChess GUI option pane .. that's because they're not defined properly :

```
option name UCI_Elo type spin default 3300 min 1100 max 3200
option name UCI_Limit type spin default 3300 min 1100 max 3200
```

the default values are higher then the max .. i'm sure this is easy to correct.

can you elaborate on these options ?
they seem an interesting setting for practical play, but confusing to me : what's their difference ? How to them (both) ? Patricia does not have MultiPV, but does e.g. UCI_Elo = 2300 mean Patricia will play let's say the fifth best move ?

**Comment by Adam-Kulju** [comment]
That bug was fixed almost immediately after release. The 3.0 release has updated exes and a note saying when the update happened and why it did.

There is no difference between the two; I had UCI_Elo support before, then added UCI_Limit because someone wanted to port Patricia into a game using UCI_Limit to weaken the engine.

UCI_Elo = 2300 means Patricia will play at a 2300 CCRL level (approximately, based on testing). The levels/elos are just the Elo strength that you're weakening her down to. (Be warned, everything over 3000 is full strength Patricia.)
